services:
  - type: web
    name: projectmind-ai
    runtime: docker
    plan: free

    rootDir: ProjectMind_AI_Erica_Nordlof
    dockerfilePath: ./Dockerfile
    dockerContext: .

    healthCheckPath: /health

    envVars:
      - key: APP_NAME
        value: ProjectMind AI

      - key: APP_PASSWORD
        sync: false

      - key: SESSION_SECRET
        generateValue: true

      - key: SESSION_SECURE
        value: "true"

      - key: OPENAI_API_KEY
        sync: false

      - key: OPENAI_MODEL
        value: gpt-5-mini

      - key: DATA_DIR
        value: /app/storage

      - key: MAX_UPLOAD_MB
        value: "50"
